// Domain constants shared across the platform.

export const CURRENCY = "KD";
export const TIMEZONE = "Asia/Kuwait";

export const ORDER_SOURCES = [
  { value: "TIKTOK", label: "TikTok" },
  { value: "INSTAGRAM", label: "Instagram" },
  { value: "WHATSAPP", label: "WhatsApp" },
  { value: "WEBSITE", label: "Website" },
] as const;

export const ORDER_STATUSES = [
  { value: "PENDING", label: "Pending" },
  { value: "PREPARING", label: "Preparing" },
  { value: "READY", label: "Ready" },
  { value: "OUT_FOR_DELIVERY", label: "Out For Delivery" },
  { value: "DELIVERED", label: "Delivered" },
  { value: "CANCELLED", label: "Cancelled" },
] as const;

export const HOUSING_TYPES = [
  { value: "HOUSE", label: "House" },
  { value: "APARTMENT", label: "Apartment" },
] as const;

export const PROJECT_STATUSES = [
  { value: "ACTIVE", label: "Active" },
  { value: "INACTIVE", label: "Inactive" },
] as const;

export const ROLES = [
  { value: "SUPER_ADMIN", label: "Super Admin" },
  { value: "ADMIN", label: "Admin" },
  { value: "EMPLOYEE", label: "Employee" },
] as const;

export const GOVERNORATES = [
  { value: "AL_ASIMAH", label: "Al Asimah" },
  { value: "HAWALLI", label: "Hawalli" },
  { value: "FARWANIYA", label: "Farwaniya" },
  { value: "AHMADI", label: "Ahmadi" },
  { value: "MUBARAK_AL_KABEER", label: "Mubarak Al Kabeer" },
  { value: "JAHRA", label: "Jahra" },
] as const;

// Areas keyed by governorate enum value. Dynamic Area dropdown reads from here.
export const AREAS_BY_GOVERNORATE: Record<string, string[]> = {
  AL_ASIMAH: [
    "Abdullah Al-Salem",
    "Adailiya",
    "Al-Sour Gardens",
    "Bnaid Al-Qar",
    "Daiya",
    "Dasman",
    "Doha",
    "Failaka Island",
    "Faiha",
    "Granada",
    "Jaber Al-Ahmad",
    "Jibla",
    "Kaifan",
    "Khaldiya",
    "Kuwait City",
    "Mansouriya",
    "Mirqab",
    "Nahdha",
    "North West Sulaibikhat",
    "Nuzha",
    "Qadsiya",
    "Qairawan",
    "Qortuba",
    "Rawda",
    "Shamiya",
    "Sharq",
    "Shuwaikh",
    "Shuwaikh Industrial",
    "Sulaibikhat",
    "Surra",
    "Yarmouk",
  ],
  HAWALLI: [
    "Al-Bidaa",
    "Al-Siddiq",
    "Anjafa",
    "Bayan",
    "Hateen",
    "Hawalli",
    "Jabriya",
    "Maidan Hawalli",
    "Mishref",
    "Mubarak Al-Abdullah",
    "Nugra",
    "Rumaithiya",
    "Salam",
    "Salmiya",
    "Salwa",
    "Shaab",
    "Shuhada",
    "Zahra",
  ],
  FARWANIYA: [
    "Abdullah Al-Mubarak",
    "Abraq Khaitan",
    "Airport",
    "Al-Dajeej",
    "Andalous",
    "Ardiya",
    "Ardiya Herafiya",
    "Farwaniya",
    "Ferdous",
    "Ishbiliya",
    "Jleeb Al-Shuyoukh",
    "Khaitan",
    "Omariya",
    "Rabia",
    "Rai",
    "Rehab",
    "Riggae",
    "Sabah Al-Nasser",
    "Shadadiya",
    "South Abdullah Al-Mubarak",
    "South Khaitan",
    "West Abdullah Al-Mubarak",
  ],
  AHMADI: [
    "Abu Halifa",
    "Ahmadi",
    "Ali Sabah Al-Salem",
    "Bar Al-Ahmadi",
    "Bnaider",
    "Dhaher",
    "Egaila",
    "Fahad Al-Ahmad",
    "Fahaheel",
    "Fintas",
    "Hadiya",
    "Jaber Al-Ali",
    "Al-Julaia'a",
    "Khairan",
    "Magwa",
    "Mahboula",
    "Mangaf",
    "Mina Abdulla",
    "Al-Nuwaiseeb",
    "Riqqa",
    "Sabah Al-Ahmad",
    "Sabah Al-Ahmad Sea City",
    "Sabahiya",
    "Shuaiba Industrial",
    "South Sabahiya",
    "Umm Al-Haiman",
    "Wafra",
    "Wafra Residential",
    "Zoor",
  ],
  MUBARAK_AL_KABEER: [
    "Abu Al Hasaniya",
    "Abu Futaira",
    "Adan",
    "Al-Masayel",
    "Fnaitees",
    "Messila",
    "Mubarak Al-Kabeer",
    "Qurain",
    "Qusour",
    "Sabah Al-Salem",
    "Sabhan",
    "West Abu Futaira Herafiya",
    "Wista",
  ],
  JAHRA: [
    "Abdali",
    "Al-Mutlaa",
    "Al-Nahda",
    "Al-Sheqaya",
    "Amghara",
    "Amghara Industrial",
    "Bahra",
    "Bar Al-Jahra",
    "Bubiyan Island",
    "Jahra",
    "Jahra Industrial",
    "Kabd",
    "Kazma",
    "Naeem",
    "Nasseem",
    "Oyoun",
    "Qasr",
    "Rawdatain",
    "Saad Al-Abdullah",
    "Sabriya",
    "Salmi",
    "Subiya",
    "Sulaibiya",
    "Taima",
    "Waha",
    "Warbah Island",
  ],
};

export type LabelValue = { value: string; label: string };

export function labelFor(list: readonly LabelValue[], value: string): string {
  return list.find((i) => i.value === value)?.label ?? value;
}
